---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client
  namespace: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-svc
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_PORT
          value: "50051"
        - name: SERVERSVC_HOST
          value: server-svc.helloworld:50051
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: glindsell/stream-meshed-client:latest
        name: client-svc
        ports:
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            cpu: 100m
status: {}
---
status: {}
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: helloworld
spec:
  selector:
    app: client-svc
  clusterIP: None
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
