---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: server
  namespace: helloworld
spec:
  replicas: 5
  selector:
    matchLabels:
      app: server-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server-svc
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GRPC_PORT
          value: "50051"
        image: glindsell/stream-meshed-server:latest
        name: server-svc
        ports:
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            cpu: 100m
---
kind: Service
apiVersion: v1
metadata:
  name: server-svc
  namespace: helloworld
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  clusterIP: 10.96.0.99
  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
---
