// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode.proto

package chaincode

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type ChaincodeMessage struct {
	TxID                 int32    `protobuf:"varint,1,opt,name=txID,proto3" json:"txID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsTX                 bool     `protobuf:"varint,3,opt,name=isTX,proto3" json:"isTX,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaincodeMessage) Reset()         { *m = ChaincodeMessage{} }
func (m *ChaincodeMessage) String() string { return proto.CompactTextString(m) }
func (*ChaincodeMessage) ProtoMessage()    {}
func (*ChaincodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{0}
}

func (m *ChaincodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeMessage.Unmarshal(m, b)
}
func (m *ChaincodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeMessage.Marshal(b, m, deterministic)
}
func (m *ChaincodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeMessage.Merge(m, src)
}
func (m *ChaincodeMessage) XXX_Size() int {
	return xxx_messageInfo_ChaincodeMessage.Size(m)
}
func (m *ChaincodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeMessage proto.InternalMessageInfo

func (m *ChaincodeMessage) GetTxID() int32 {
	if m != nil {
		return m.TxID
	}
	return 0
}

func (m *ChaincodeMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChaincodeMessage) GetIsTX() bool {
	if m != nil {
		return m.IsTX
	}
	return false
}

func init() {
	proto.RegisterType((*ChaincodeMessage)(nil), "chaincode.ChaincodeMessage")
}

func init() { proto.RegisterFile("chaincode.proto", fileDescriptor_97136ef4b384cc22) }

var fileDescriptor_97136ef4b384cc22 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0x48, 0xcc,
	0xcc, 0x4b, 0xce, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x85, 0x70, 0x09, 0x38, 0xc3, 0x38, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x42, 0x5c,
	0x2c, 0x25, 0x15, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x04,
	0x17, 0x7b, 0x2e, 0x44, 0x5a, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x05, 0xa9, 0xce,
	0x2c, 0x0e, 0x89, 0x90, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x08, 0x02, 0xb3, 0x8d, 0x62, 0xb8, 0x38,
	0xe1, 0xa6, 0x0a, 0xf9, 0x73, 0xf1, 0xc2, 0x39, 0xce, 0x19, 0x89, 0x25, 0x42, 0xd2, 0x7a, 0x08,
	0x07, 0xa1, 0x5b, 0x2e, 0x85, 0x4f, 0x52, 0x89, 0x41, 0x83, 0xd1, 0x80, 0xd1, 0x49, 0x8f, 0x4b,
	0x2a, 0x33, 0x5f, 0x2f, 0xbd, 0xa8, 0x20, 0x59, 0x2f, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5,
	0x18, 0xa1, 0xc9, 0x89, 0x0f, 0xae, 0x2b, 0x00, 0xe4, 0xd9, 0x00, 0xc6, 0x24, 0x36, 0xb0, 0xaf,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xc5, 0x06, 0x6b, 0x08, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaincodeClient is the client API for Chaincode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaincodeClient interface {
	// Sends a greeting
	ChaincodeChat(ctx context.Context, opts ...grpc.CallOption) (Chaincode_ChaincodeChatClient, error)
}

type chaincodeClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeClient(cc *grpc.ClientConn) ChaincodeClient {
	return &chaincodeClient{cc}
}

func (c *chaincodeClient) ChaincodeChat(ctx context.Context, opts ...grpc.CallOption) (Chaincode_ChaincodeChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chaincode_serviceDesc.Streams[0], "/chaincode.Chaincode/ChaincodeChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeChaincodeChatClient{stream}
	return x, nil
}

type Chaincode_ChaincodeChatClient interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ClientStream
}

type chaincodeChaincodeChatClient struct {
	grpc.ClientStream
}

func (x *chaincodeChaincodeChatClient) Send(m *ChaincodeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chaincodeChaincodeChatClient) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChaincodeServer is the server API for Chaincode service.
type ChaincodeServer interface {
	// Sends a greeting
	ChaincodeChat(Chaincode_ChaincodeChatServer) error
}

func RegisterChaincodeServer(s *grpc.Server, srv ChaincodeServer) {
	s.RegisterService(&_Chaincode_serviceDesc, srv)
}

func _Chaincode_ChaincodeChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChaincodeServer).ChaincodeChat(&chaincodeChaincodeChatServer{stream})
}

type Chaincode_ChaincodeChatServer interface {
	Send(*ChaincodeMessage) error
	Recv() (*ChaincodeMessage, error)
	grpc.ServerStream
}

type chaincodeChaincodeChatServer struct {
	grpc.ServerStream
}

func (x *chaincodeChaincodeChatServer) Send(m *ChaincodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chaincodeChaincodeChatServer) Recv() (*ChaincodeMessage, error) {
	m := new(ChaincodeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chaincode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chaincode.Chaincode",
	HandlerType: (*ChaincodeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChaincodeChat",
			Handler:       _Chaincode_ChaincodeChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chaincode.proto",
}
